import math

class Params:
    WIDTH = 1920
    HEIGHT = 1000
    CENTER = [WIDTH / 2, HEIGHT / 2]
    
    MAX_DIST_TO_MIDDLE = math.dist([0, 0], CENTER)
    MAX_TOWER_DIST = MAX_DIST_TO_MIDDLE * 0.3
    MAX_BARRACKS_DIST = MAX_DIST_TO_MIDDLE * 0.5
    
    TOWER_TARGET_RADIUS = 500
    
    SAVING_LIMIT = 200